first try
simonkrivonosov/smart-home-2019 pull request #1
Opened 2019-10-10 20:58 UTC by simonkrivonosov

2019-10-13 20:07 UTC, a-ivanov commented
Удалите из коммитов директорию target/classes/ru/sbt/mipt/oop и файл smart-home.iml с настройками Intellij Idea. Добавьте правила в .gitignore. Эти файлы не являются частью исходного кода проекта.

2019-10-13 20:35 UTC, a-ivanov requested changes

2019-10-13 20:35 UTC, a-ivanov commented on smart-home.iml
> +<?xml version="1.0" encoding="UTF-8"?>
В .gitignore и удалите из коммита.

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private static SmartHomeLoader smartHomeLoader = new JsonSmartHomeLoader();
Для удобства чтения кода эти переменные можно перенести в main метод. Тогда и не придется делать seter'ы (mutability здесь не дает особой выгоды).

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public static void setSmartHomeLoader(SmartHomeLoader smartHomeLoader, CommandSender commandSender) {
Добавляйте расстояние между методом и полем.

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeLoader.java
> +    SmartHome loadSmartHome(Object source) throws IOException;
А если мы захотим получать состояние дома через сеть? Здесь детали имплементации видны снаружи, в абстракции (leaky abstraction).
Исправьте.

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ConcreteCommandSender.java
> +public class ConcreteCommandSender implements CommandSender {
Способ имплементации нужно отражать в названии класса (для имплементационного класса, но не в коем случае для абстракции). Concrete не говорит ни о чем его пользователям.
Исправьте.

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeEventObserver.java
> +        while (event != null) {
Цикл обработки событий - это отдельная responsibility. Сейчас нарушается SRP.
Исправьте.

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeEventObserver.java
> +        SensorEventProvider randomSensorEventProvider = new RandomSensorEventProvider();
А если мы захотим поменять способ получения событий (например, от настоящего внешнего сенсора через стороннюю библиотеку)? Тогда нам придется менять код внутри класса с бизнес-логикой (обработка событий). Здесь нарушается OCP.
Исправьте.

2019-10-13 20:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +public class Door implements HomeEntity{
Является ли обработка события обязанностью двери (то же самое для Light)? А если мы захотим добавить больше событий для двери? То придется менять код внутри двери. Здесь нарушается OCP - нам придется менять, а не добавлять новый код (класс) для новой функциональности.
Подумайте, в каком классе лучше разместить логику HomeEntity и исправьте.

2019-10-13 20:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> -                                if (room.getName().equals("hall")) {
А где ваша реализация логики "умного" дома (событие закрытия входной двери)?

2019-10-17 17:57 UTC, simonkrivonosov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeLoader.java
> +    SmartHome loadSmartHome(Object source) throws IOException;
Насчет получения состояния дома через сеть: имеется ввиду, что плохое название? или что loadSmartHome не должен получать аргумент, а хранить путь в качестве атрибута и принимать в конструкторе?

2019-10-26 19:59 UTC, a-ivanov commented
Закройте этот реквест, если все исправления по 1 дз в https://github.com/simonkrivonosov/smart-home-2019/pull/2.

2019-10-31 15:33 UTC, closed without merging